[package]
name = "s3-simple-artifact-handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
log = "0.4.22"
minio = "0.1.0"
tokio = "1.39.2"
