version: '3'

services:
  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - '9005:9000'
      - '9006:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=your_username
      - MINIO_ROOT_PASSWORD=your_pasword
      - MINIO_DEFAULT_BUCKETS=bucket

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local