name: Release Application

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
    tags:
      - '*'
    types:
      - started
      - created
      - completed
    condition: ${{ contains(github.event.head_commit.message, '[release]') }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build application
        run: cargo build --release

      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: target/release/

  create_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: ./binaries

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./binaries/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}