name: Release Application

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
    # tags:
    #   - '*'
    # types:
    #   - started
    #   - created
    #   - completed
    # condition: ${{ contains(github.event.head_commit.message, '[release]') }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true

      - name: Build application
        env:
          OPENSSL_STATIC: yes
          OPENSSL_INCLUDE_DIR: /usr/include/openssl
          OPENSSL_LIB_DIR: /usr/lib64 
        run: cargo build --release

      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: target/release/s3-simple-artifact-handler

  create_tag_and_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Tag
        id: tag_step
        run: |
          VERSION=$(date +'%Y.%m.%d-%H%M%S')
          git tag $VERSION
          git push origin $VERSION
          echo "::set-output name=TAG_NAME::$VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: ./binaries

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_step.outputs.tag_name }}
          files: ./binaries/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}